### ISSUE TITLE
Count_operator README in Github needs an improvement

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/count_operator#1]
https://github.com/tercen/count_operator/tree/0.10.0

Usage of this operator written in README is not very clear, "input projection" in particular. For example, to count the cell number (event number) per sample (filename), this operator requires factors in Y-axis (e.g. value) and column (e.g. filename). 

Output:  Y-axis: counts, column: filename/sample 

It is the best to automatically choose Bar as a default projection, instead of a dot.

**Comment by agouy** [comment]
I have improved the documentation. Regarding using the bar as a default projection, this is not possible at the moment - it would require some more extensive work on the tercen side, which might not be the effort for now.

**Comment by emaurel** [comment]
Starting the process to fetch branches and create the 'specs' branch if it doesn't exist for the count_operator repository. via AI
