### ISSUE TITLE
Count operator output Y-axis scale is not starting from 0 (Zero)

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/count_operator#2]
The Y-axis scale is not starting from 0 (zero) and the lowest scale shows up on the Y-axis of the result is set based on the lowest count value, which makes the impression that the lowest count sample has hardly any counts, which is not true and is misleading. If the count number is very large or wide spread between the filenames, we should be able to choose log-scale or spread the bar in 2 parts (by providing a high/low separation criteria, for instance). The choice of linear or log scale should be provided as a optional. 
![Image](https://user-images.githubusercontent.com/87133370/178221294-afb09739-435f-4a57-bf83-a941f7bf1737.png)

**Comment by agouy** [comment]
I agree that we need to have the y axis set to 0 when using bars. Closing this issue as I have written the issue already here:
https://github.com/tercen/sci/issues/144
